"""Measure activation amax for the FP8 conv path and write vsrlib/fp8_conv_scales.py.

Runs the stock bf16 tiny-long pipeline on a few crops of real videos and records,
for every TCDecoder conv input / MemBlock output and both LQ-projector conv
inputs, the largest |value| seen. fp8_conv derives power-of-two scales from these
with headroom, so a handful of representative clips is enough.

    python tools/calibrate_fp8_conv.py -v 11 inputs/example0.mp4 inputs/example3.mp4 ...

Each input is processed as a centered crop at scale 2 (--crop2, 512px output,
the jasna inline shape) and at scale 4 (--crop4). Existing tables for other
versions are kept.
"""
import argparse
import os
import pprint
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from vsrlib.common import log, root  # noqa: E402  (before torch)

import torch  # noqa: E402

from src.models import wan_video_dit  # noqa: E402
from src.models.TCDecoder import MemBlock  # noqa: E402
from vsrlib.engine import init_pipeline  # noqa: E402
from vsrlib.media_io import probe_input  # noqa: E402
from vsrlib.preprocess import get_input_params_from_dims, stream_tile_frames  # noqa: E402
from vsrlib.fp8_conv import lq_convs  # noqa: E402
from vsrlib import fp8_conv_scales  # noqa: E402


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("inputs", nargs="+")
    ap.add_argument("-v", "--version", default="11", choices=["10", "11"])
    ap.add_argument("--crop2", type=int, default=256)
    ap.add_argument("--crop4", type=int, default=192)
    ap.add_argument("--max-frames", type=int, default=97)
    args = ap.parse_args()

    device = "cuda:0"
    wan_video_dit.USE_BLOCK_ATTN = False
    pipe = init_pipeline(args.version, "tiny-long", device, torch.bfloat16)
    amax = {"tcd": {}, "lq": {}}

    def rec(group, key, t):
        v = float(t.detach().abs().amax())
        amax[group][key] = max(amax[group].get(key, 0.0), v)

    # Hooks must return None (a non-None return replaces the args / output).
    def pre(group, key):
        def hook(mod, a):
            rec(group, key, a[0])
            if len(a) > 1 and isinstance(a[1], torch.Tensor):  # LQ causal cache
                rec(group, key, a[1])
        return hook

    def post(group, key):
        def hook(mod, a, out):
            rec(group, key, a[0])
            rec(group, key, out)
        return hook

    hooks = []
    for name, m in pipe.TCDecoder.decoder.named_modules():
        if isinstance(m, torch.nn.Conv2d):
            hooks.append(m.register_forward_pre_hook(pre("tcd", f"decoder.{name}")))
        if isinstance(m, MemBlock):
            # the stage scale covers a MemBlock's input (conv.0 sees cat(x, past)) and output
            hooks.append(m.register_forward_hook(post("tcd", f"decoder.{name}")))
    for name, m in lq_convs(pipe.denoising_model().LQ_proj_in):
        hooks.append(m.register_forward_pre_hook(pre("lq", name)))

    out_path = os.path.join(root, "_temp", "calibrate_out.mp4")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    for path in args.inputs:
        kind, source, N0, h0, w0, _fps = probe_input(path)
        N0 = min(N0, args.max_frames)
        for scale, crop in ((2, args.crop2), (4, args.crop4)):
            c = min(crop, h0, w0)
            y1, x1 = (h0 - c) // 2, (w0 - c) // 2
            th, tw, F = get_input_params_from_dims(N0, c, c, scale)
            LQ = stream_tile_frames(kind, source, x1, y1, x1 + c, y1 + c, N0, F, device,
                                    scale=scale, tW=tw, tH=th, dtype=torch.bfloat16)
            log(f"[calibrate] {os.path.basename(path)} scale {scale} crop {c}", message_type="info")
            ok = pipe(prompt="", negative_prompt="", cfg_scale=1.0, num_inference_steps=1, seed=0,
                      tiled=False, LQ_video=LQ, num_frames=F, height=th, width=tw, is_full_block=False,
                      if_buffer=True, topk_ratio=2 * 768 * 1280 / (th * tw), kv_ratio=3, local_range=11,
                      color_fix=False, unload_dit=False, fps=30, quality=6, output_path=out_path, tiled_dit=True)
            if ok is not True:
                raise SystemExit("pipeline failed")
    for h in hooks:
        h.remove()
    os.remove(out_path)

    table = dict(fp8_conv_scales.AMAX)
    table[args.version] = {g: {k: round(v, 4) for k, v in sorted(d.items())} for g, d in amax.items()}
    dst = os.path.join(root, "vsrlib", "fp8_conv_scales.py")
    with open(dst, "w", encoding="utf-8", newline="\n") as f:
        f.write("# Calibrated activation amax for the FP8 convolutions (vsrlib/fp8_conv.py), keyed\n"
                "# by model version. Generated by tools/calibrate_fp8_conv.py — do not edit by\n"
                "# hand; bump the fp8_conv part versions in vsrlib/accel.py when regenerating,\n"
                "# since the scales change the output (and so the --resume manifest).\n")
        f.write("AMAX = " + pprint.pformat(table, width=100, sort_dicts=True) + "\n")
    log(f"[calibrate] wrote {dst}", message_type="finish")


if __name__ == "__main__":
    main()
